### ISSUE TITLE
Modify CSS and HTML to improve website adaptibility

### ISSUE THREAD

**Issue by omgaikwad99** [EECE3093C/team-project-nontoastermakers#31]

**Comment by mabonmn** [comment]
@omgaikwad99 @muhibkhn  ALl pages are linked. Please fix CSS ASAP
Mabon

**Comment by mabonmn** [comment]
@omgaikwad99 @muhibkhn Please ref this issue for the branch

**Comment by muhibkhn** [comment]
Done with the css for the html files. Please let me know if we need anything to be changed. -Muhib
