### ISSUE TITLE
Admin Page 

### ISSUE THREAD

**Issue by mabonmn** [EECE3093C/team-project-nontoastermakers#46]
Develope and libnk a new admin page based on spec discuessed in meeting

**Comment by mabonmn** [comment]
@omgaikwad99  Please fix the contact page

**Comment by omgaikwad99** [comment]
Removed base.html stuff from the home page

**Comment by omgaikwad99** [comment]
added css to admin page

**Comment by omgaikwad99** [comment]
1. remove home option from the home page
2. remove about and menu options from menu page
3.  Fix the linking of the home page in menu page.
4. Add a home button in the admin page
