### ISSUE TITLE
Bug Fixes ( Cosmetic)

### ISSUE THREAD

**Issue by mabonmn** [EECE3093C/team-project-nontoastermakers#55]
Fix login page
Add link to home page
Add CSS to Register page
Make sure there is a logical transition from one page to another

**Comment by mabonmn** [comment]
@itsmfz  branch updated

**Comment by mabonmn** [comment]
Great job @itsmfz

**Comment by mabonmn** [comment]
@muhibkhn Branch has been corupted . USE THE NEW BRANMCH LINKED WITH THIS ISSUE

**Comment by mabonmn** [comment]
55-bug-fixes-cosmetic-1

**Comment by muhibkhn** [comment]
on it!

**Comment by muhibkhn** [comment]
@mabonmn In this branch, I do not see any page other than login and sign up when I open the webpage from the branch.

**Comment by muhibkhn** [comment]
Have added css files, more work to be done on it, I have static header and footers going on. Linking pictures on codespace is a bit weird. Figuring that out.

**Comment by mabonmn** [comment]
@muhibkhn Great job.. Keep at it.
