### ISSUE TITLE
Unit Testing 

### ISSUE THREAD

**Issue by mabonmn** [EECE3093C/team-project-nontoastermakers#63]

**Comment by omgaikwad99** [comment]
[Unit Testing.docx](https://github.com/EECE3093C/team-project-nontoastermakers/files/11216736/Unit.Testing.docx)

**Comment by omgaikwad99** [comment]
@mabonmn The required documentation has been added, meticulously outlining the test cases and accompanying screenshots for reference. Kindly review and provide feedback on any necessary alterations or adjustments that may be required for completeness and accuracy.

**Comment by mabonmn** [comment]
PLEASE NOTE THAT THIS WAS WORKDE ON BY OM GAIKWAD AND MABON NINAN
