### ISSUE TITLE
Broken Add to cart

### ISSUE THREAD

**Issue by mabonmn** [EECE3093C/team-project-nontoastermakers#70]
Hey muhib, pls check this feature? Evan feel free to pitch in on this. If muhib needs help you may consult on this branch

**Comment by muhibkhn** [comment]
Fix has been made. Please review.

**Comment by mabonmn** [comment]
looks good

**Comment by nimmoev** [comment]
Hi, after merge to #72 53 Checkout Functionality images on menu page still do not show.  Is this the bug Mabon is referring to?

**Comment by mabonmn** [comment]
Merge Complete
